application: gcdc2013-webtalks
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
 - name: django
   version: 1.4

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'webtalks.settings'